### ISSUE TITLE
No `heytmux` installed with vim plugin method

### ISSUE THREAD

**Issue by turboladen** [junegunn/heytmux#2]
I installed heytmux using plug, but don't end up with a `heytmux` command available in my PATH. ...thus am not quite sure how to launch the new tmux session. I'm a ruby user so I certainly don't mind installing the gem, but just figured it'd be more convenient to use the vim plugin since I tend to switch ruby versions from time to time.

```
 ❯ nvim --version                                                                                              ⏎ ✹ ✭ [ruby-2.4.1]
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170503-26228-1koxlmx/neovim-0.2.0/build/config -I/tmp/neovim-20170503-26228-1koxlmx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170503-26228-1koxlmx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170503-26228-1koxlmx/neovim-0.2.0/build/include
Compiled by sloveless@sloveless-mbp.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"
```

**Comment by junegunn** [comment]
> but don't end up with a heytmux command available in my PATH

Maybe I should have been more clear about that. It doesn't install gem on your system, instead it executes heytmux [directly with `-I lib` flag](https://github.com/junegunn/heytmux/blob/master/plugin/heytmux.vim#L42-L43), so who only want Heytmux inside Vim don't have to install gem on their system.

I'm not sure how I should do about it, but for now you can tell vim-plug to run `gem install` whenever the repo is updated.

```vim
Plug 'junegunn/heytmux', { 'do': 'gem install heytmux' }
```

**Comment by junegunn** [comment]
Updated the instruction here: https://github.com/junegunn/heytmux/commit/84dc19a3c94a2bc03dd9ed6ad5dd4c87a16148e6

**Comment by turboladen** [comment]
> it executes heytmux directly with -I lib flag,

Ah, that makes more sense. Thanks for the quick response and vim-plug suggestion!
